### ISSUE TITLE
Wordpress instance sporadically has database connectivity issues

### ISSUE THREAD

**Issue by CaptainCalliope** [ActCal/activistcalendar#74]
The website occasionally goes offline with database connectivity error messages. Sometimes it's for 5 minutes, other times for up to 2-3 hours. :O

Must diagnose and fix before sharing the website far and wide!

**Comment by thecristen** [comment]
The logs show many instances of the following: `[ERROR] InnoDB: Cannot allocate memory for the buffer pool`

**Comment by thecristen** [comment]
The debugging commands in [this help article](https://www.digitalocean.com/community/tutorials/how-to-protect-wordpress-from-xml-rpc-attacks-on-ubuntu-14-04) produced some output. We're experiencing XML-RPC attacks! Gonna try the second method noted in the article to fix that.

**Comment by thecristen** [comment]
nope, didn't help. mysql keeps running out of memory
<img width="733" alt="image" src="https://user-images.githubusercontent.com/2136286/33916892-36193494-df79-11e7-8bcd-81a796814d1e.png">

here's how much space we're working with here
<img width="727" alt="image" src="https://user-images.githubusercontent.com/2136286/33916919-5a51a2ce-df79-11e7-93b7-aa5628fd5029.png">

will keep investigating..

**Comment by thecristen** [comment]
tried the apache tweak [mentioned here](https://www.digitalocean.com/community/questions/mysql-server-keeps-stopping-unexpectedly?answer=26016) and the mysql buffer adjustment [mentioned here](http://www.webtrafficexchange.com/solved-mysql-crash-fatal-error-cannot-allocate-memory-buffer-pool)

**Comment by hurtstotouchfire** [comment]
Do we have DB monitoring set up so that we can tell if these changes are improving it? Like, are there graphs somewhere?
